package com.zarisa.ezmart.model

data class Product(
    val id: Int,
    val images: List<Image>,
    val name: String,
    val categories: List<Category>?,
    val description: String,
    val price: String,
    val short_description: String,
    val total_sales: Int,
    val on_sale: Boolean,
    val rating_count: Int?,
    val sale_price: String,
    val average_rating: String?,
    val tags: List<Tag>,
    val attributes:List<Attribute>?,
    val date_created: String,
    val date_created_gmt: String,
    val related_ids: List<Int>,
)

/*

val _links: Links,
val backordered: Boolean,
val backorders: String,
val backorders_allowed: Boolean,
val button_text: String,
val catalog_visibility: String,
val cross_sell_ids: List<Any>,
val date_modified: String,
val date_modified_gmt: String,
val date_on_sale_from: Any,
val date_on_sale_from_gmt: Any,
val date_on_sale_to: Any,
val date_on_sale_to_gmt: Any,
val default_attributes: List<Any>,
val dimensions: Dimensions,
val download_expiry: Int,
val download_limit: Int,
val downloadable: Boolean,
val downloads: List<Any>,
val external_url: String,
val featured: Boolean,
val grouped_products: List<Any>,
val low_stock_amount: Any,
val manage_stock: Boolean,
val menu_order: Int,
val meta_data: List<Any>,
val parent_id: Int,
val permalink: String,
val price_html: String,
val purchasable: Boolean,
val purchase_note: String,
val regular_price: String,
val reviews_allowed: Boolean,
val shipping_class: String,
val shipping_class_id: Int,
val shipping_required: Boolean,
val shipping_taxable: Boolean,
val sku: String,
val slug: String,
val sold_individually: Boolean,
val status: String,
val stock_quantity: Any,
val stock_status: String,
val tax_class: String,
val tax_status: String,
val type: String,
val upsell_ids: List<Any>,
val variations: List<Any>,
val virtual: Boolean,
val weight: String
 */